services:
  # Background Worker - Database Initialization (FREE TIER)
  - type: worker
    name: odoo-db-init
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: /init-db.sh
    envVars:
      - key: PGHOST
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGSSLMODE
        value: require
    # This worker runs once on deploy to initialize the DB
    autoDeploy: true

  # COMMENTED OUT - Uncomment when ready to add web service (requires payment)
  # - type: web
  #   name: odoo-web
  #   env: docker
  #   dockerfilePath: ./Dockerfile
  #   dockerCommand: /entrypoint.sh
  #   envVars:
  #     - key: PGHOST
  #       sync: false
  #     - key: PGPORT
  #       sync: false
  #     - key: PGUSER
  #       sync: false
  #     - key: PGPASSWORD
  #       sync: false
  #     - key: PGDATABASE
  #       sync: false
  #     - key: PGSSLMODE
  #       value: require
  #   healthCheckPath: /web/health
  #   autoDeploy: true

databases:
  # This references your existing Aiven PostgreSQL database
  # You'll connect it via environment variables above
  # No need to create a new database in Render
  []
