services:
  - type: web
    name: odoo
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /web/health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8069
      # Use internal connection - no SSL needed within Render's network
      - key: PGHOST
        value: odoo-db
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        value: odoo_6rk7
      - key: PGUSER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      # Disable SSL for internal connections
      - key: PGSSLMODE
        value: disable

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo_6rk7
    user: odoo