services:
  - type: web
    name: odoo
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /web/health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8069
      # Use PG* prefix to match what psycopg2 expects
      - key: PGHOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: odoo-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: odoo-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      # Force SSL mode for Render's PostgreSQL
      - key: PGSSLMODE
        value: require

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo
    user: odoo