name: Reset and Initialize Odoo Database

on:
  # Manual trigger only - you control when to run this
  workflow_dispatch:
    inputs:
      confirm_reset:
        description: 'Type "RESET" to confirm database deletion'
        required: true
        default: ''
  
  # OR uncomment below to run automatically on push to main
  # push:
  #   branches:
  #     - main

jobs:
  reset-and-init-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Validate confirmation
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "RESET" ]; then
            echo "❌ Confirmation failed. You must type 'RESET' to proceed."
            exit 1
          fi
          echo "✅ Confirmation received. Proceeding with database reset..."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Clear all data from database (safer than drop/create)
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          echo "🧹 Clearing all tables from database: ${PGDATABASE}"
          
          # This approach works even without DROP DATABASE permissions
          # It removes all Odoo tables so init-db.sh will treat it as empty
          
          PGPASSWORD="${PGPASSWORD}" psql -h "${PGHOST}" -p "${PGPORT}" -U "${PGUSER}" -d "${PGDATABASE}" << 'EOF'
          DO $ 
          DECLARE
              r RECORD;
          BEGIN
              -- Drop all tables in public schema
              FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') 
              LOOP
                  EXECUTE 'DROP TABLE IF EXISTS public.' || quote_ident(r.tablename) || ' CASCADE';
              END LOOP;
              
              -- Drop all sequences
              FOR r IN (SELECT sequence_name FROM information_schema.sequences WHERE sequence_schema = 'public')
              LOOP
                  EXECUTE 'DROP SEQUENCE IF EXISTS public.' || quote_ident(r.sequence_name) || ' CASCADE';
              END LOOP;
              
              -- Drop all views
              FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public')
              LOOP
                  EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
              END LOOP;
              
              RAISE NOTICE '✅ Database cleared successfully';
          END $;
          EOF
          
          echo "✅ All Odoo data removed from database"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build initialization Docker image
        run: |
          echo "🏗️  Building Docker image for initialization..."
          docker build -f Dockerfile.init -t odoo-init .

      - name: Run database initialization
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          echo "🚀 Initializing Odoo with GMailer addon..."
          docker run --rm \
            -e PGHOST="${PGHOST}" \
            -e PGPORT="${PGPORT}" \
            -e PGUSER="${PGUSER}" \
            -e PGPASSWORD="${PGPASSWORD}" \
            -e PGDATABASE="${PGDATABASE}" \
            -e PGSSLMODE="${PGSSLMODE}" \
            odoo-init

      - name: Initialization Complete
        run: |
          echo "✅ Database reset and initialization completed successfully!"
          echo ""
          echo "📋 Summary:"
          echo "  • Old database dropped"
          echo "  • Fresh database created"
          echo "  • Odoo base modules installed"
          echo "  • GMailer addon installed"
          echo ""
          echo "🔐 Default credentials:"
          echo "  Username: admin"
          echo "  Password: admin"
          echo ""
          echo "Your Odoo database is now ready to use!"
