name: Initialize Odoo Database

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Database Action'
        required: true
        type: choice
        options:
          - 'Install GMailer (keep existing data)'
          - 'Complete Database Reset (DANGER: deletes all data)'
        default: 'Install GMailer (keep existing data)'

jobs:
  init-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build initialization Docker image
        run: docker build -f Dockerfile.init -t odoo-init .

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Complete Database Reset
        if: github.event.inputs.action == 'Complete Database Reset (DANGER: deletes all data)'
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          echo "WARNING: Dropping all tables from database..."
          echo "Database: ${PGDATABASE}"
          echo ""
          
          PGPASSWORD="${PGPASSWORD}" psql -h "${PGHOST}" -p "${PGPORT}" -U "${PGUSER}" -d "${PGDATABASE}" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO ${PGUSER}; GRANT ALL ON SCHEMA public TO public;"
          
          echo "Database wiped clean!"
          echo ""

      - name: Run database initialization
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          echo "Starting database initialization..."
          echo "Action: ${{ github.event.inputs.action }}"
          echo ""
          
          docker run --rm \
            -e PGHOST="${PGHOST}" \
            -e PGPORT="${PGPORT}" \
            -e PGUSER="${PGUSER}" \
            -e PGPASSWORD="${PGPASSWORD}" \
            -e PGDATABASE="${PGDATABASE}" \
            -e PGSSLMODE="${PGSSLMODE}" \
            odoo-init

      - name: Initialization Complete
        run: |
          echo ""
          echo "Database operation completed successfully!"
          echo ""
          if [ "${{ github.event.inputs.action }}" == "Complete Database Reset (DANGER: deletes all data)" ]; then
            echo "Database has been completely reset and reinitialized"
            echo "Installed modules: base, account, sale_management, GMailer"
            echo "Login credentials: admin / admin"
          else
            echo "GMailer module has been installed/updated"
            echo "Use your existing login credentials"
          fi
          echo ""
          echo "Your Odoo database is now ready to use."
