name: Initialize Odoo Database

on:
  workflow_dispatch:

jobs:
  init-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build initialization Docker image
        run: |
          echo "🏗️  Building Docker image..."
          docker build -f Dockerfile.init -t odoo-init .

      - name: Run database initialization with retry
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGSSLMODE: require
        run: |
          echo "🚀 Initializing Odoo (will retry on lock timeout)..."
          
          MAX_RETRIES=3
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
            
            if docker run --rm \
              -e PGHOST="${PGHOST}" \
              -e PGPORT="${PGPORT}" \
              -e PGUSER="${PGUSER}" \
              -e PGPASSWORD="${PGPASSWORD}" \
              -e PGDATABASE="${PGDATABASE}" \
              -e PGSSLMODE="${PGSSLMODE}" \
              odoo-init; then
              echo "✅ Initialization successful!"
              exit 0
            else
              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "⚠️ Initialization failed, waiting 30 seconds before retry..."
                sleep 30
              else
                echo "❌ All retries exhausted"
                exit 1
              fi
            fi
          done

      - name: Initialization Complete
        run: |
          echo "✅ Database initialization completed!"
          echo ""
          echo "🔐 Default credentials:"
          echo "  Username: admin"
          echo "  Password: admin"
